on:
  push:
    branches:
      - release/*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: deeepvision/github-action-docker-build@release/1.0
        with:
          name: ci-node
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: deeepvision/github-action-docker-hub@release/1.0
        with:
          githubName: ci-node
          dockerHubUser: ${{ secrets.DOCKERHUB_USER }}
          dockerHubPassword: ${{ secrets.DOCKERHUB_PASS }}
          dockerHubName: deeepvision/ci-node
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
