name: Publish Docker Image

on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: ./.github/actions/docker-build
        env:
          GITHUB_DOCKER_TOKEN: ${{ secrets.GITHUB_DOCKER_TOKEN }}
